export { default as id } from "./id.js";
export { default as title } from "./title.js";
export { default as description } from "./description.js";
export { default as images } from "./images.js";
export { default as subcategory } from "./subcategory.js";
export { default as price } from "./price.js";
export { default as discount } from "./discount.js";
export { default as quantity } from "./quantity.js";
export { default as status } from "./status.js";
